// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBX07kQFyhtqyxURX1_lf_O-Va0YqcHc',
    appId: '1:972337351306:web:6bfa465d37cfc81e4ffb73',
    messagingSenderId: '972337351306',
    projectId: 'fir-3f06d',
    authDomain: 'fir-3f06d.firebaseapp.com',
    storageBucket: 'fir-3f06d.firebasestorage.app',
    measurementId: 'G-VWYLLVX34B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh3ajbgQ6fl32-wC-rpt4DhgjSpV6hBbY',
    appId: '1:972337351306:android:95c1454f60125b7d4ffb73',
    messagingSenderId: '972337351306',
    projectId: 'fir-3f06d',
    storageBucket: 'fir-3f06d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPPOoDFEmzI0Tb65xuSEZ8kmJCkbGkMoE',
    appId: '1:972337351306:ios:dd45ac2e6a95c7604ffb73',
    messagingSenderId: '972337351306',
    projectId: 'fir-3f06d',
    storageBucket: 'fir-3f06d.firebasestorage.app',
    iosBundleId: 'com.example.interactive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPPOoDFEmzI0Tb65xuSEZ8kmJCkbGkMoE',
    appId: '1:972337351306:ios:dd45ac2e6a95c7604ffb73',
    messagingSenderId: '972337351306',
    projectId: 'fir-3f06d',
    storageBucket: 'fir-3f06d.firebasestorage.app',
    iosBundleId: 'com.example.interactive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpBX07kQFyhtqyxURX1_lf_O-Va0YqcHc',
    appId: '1:972337351306:web:f2d4ce9c9101a9704ffb73',
    messagingSenderId: '972337351306',
    projectId: 'fir-3f06d',
    authDomain: 'fir-3f06d.firebaseapp.com',
    storageBucket: 'fir-3f06d.firebasestorage.app',
    measurementId: 'G-RWEJ7EEF2B',
  );
}
